- hosts: all
  sudo: True
  tasks:
    - include: 'tasks/main.yml'
  handlers:
    - include: 'handlers/main.yml'
  vars_files:
    - 'defaults/main.yml'

  vars:

    #prometheus_components: [ "prometheus" ]
    #prometheus_components: [ "node_exporter" ]
    #prometheus_components: [ "alertmanager" ]
    prometheus_components: [ "prometheus", "node_exporter", "alertmanager", "consul_exporter" ]

    prometheus_rule_files:
      this_is_rule_1_InstanceDown:
        src:  test/basic.rules
        dest: basic.rules

    prometheus_alertmanager_url: "http://localhost:9093/"

    prometheus_alertmanager_conf: test/alertmanager.conf.j2

  roles:
    - { role: consul,
        consul_is_server: true }

  post_tasks:
    - name: copy file_sd
      copy: src="{{ playbook_dir }}/test/file_sd.yml"  dest={{ prometheus_file_sd_config_path }}
