#
# Top-level installer tools required for compiling Prometheus sources.
#

---

- name: install dependencies for installation of components from source
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - git
    - gzip
    - curl
    - gcc

- name: install make
  yum: name=make state=present update_cache=yes
  when: ansible_pkg_mgr == "yum"

- name: install make
  apt: name=build-essential state=present update_cache=yes
  when: ansible_pkg_mgr == "apt"

- name: set internal variables for convenience
  set_fact:
    prometheus_golang_tarball_url: "https://storage.googleapis.com/golang/go{{ prometheus_go_version }}.{{ prometheus_platform_suffix }}.tar.gz"

- name: mkdir for Golang
  file: path={{ item }}  state=directory
  with_items:
    - "{{ prometheus_goroot }}"
    - "{{ prometheus_gopath }}"

- name: download and untar Golang tarball
  unarchive:
    src:  "{{ prometheus_golang_tarball_url }}"
    dest: "{{ prometheus_workdir }}"
    copy: no
    creates: "{{ prometheus_goroot }}/bin/go"
