#
# Install "gosu" utility.
#
# @see https://github.com/tianon/gosu
#

- name: Register the gosu_arch variable
  shell: "dpkg --print-architecture | awk -F- '{ print $NF }'"
  check_mode: no
  register: gosu_arch

- name: set internal variables for convenience
  set_fact:
    gosu_exe_url: "https://github.com/tianon/gosu/releases/download/{{ gosu_version }}/gosu-{{ gosu_arch.stdout }}"

- name: download gosu executable
  get_url: url="{{ gosu_exe_url }}"  dest="/usr/local/bin/gosu"

- name: add executable permission
  file: path="/usr/local/bin/gosu" state=file mode="a+x"
