---
# file: tasks/install-prometheus.yml
#
# Install Prometheus server.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- name: set internal variables for convenience
  set_fact:
    prometheus_tarball_url: "https://github.com/prometheus/prometheus/releases/download/{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    prometheus_untar_path: "{{ prometheus_install_path }}"
    prometheus_subdir: "{{ prometheus_install_path }}/prometheus-{{ prometheus_version }}.linux-amd64"
  when: prometheus_version != "git"  and  ansible_userspace_bits == "64"

- name: set internal variables for convenience
  set_fact:
    prometheus_tarball_url: "https://github.com/prometheus/prometheus/releases/download/{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-386.tar.gz"
    prometheus_untar_path: "{{ prometheus_install_path }}"
    prometheus_subdir: "{{ prometheus_install_path }}/prometheus-{{ prometheus_version }}.linux-386"
  when: prometheus_version != "git"  and  ansible_userspace_bits == "32"

- name: set internal variables for convenience
  set_fact:
    prometheus_tarball_url: "https://github.com/prometheus/prometheus/archive/master.tar.gz"
    prometheus_untar_path: "{{ prometheus_download_path }}/prometheus_workdir/gopath/src/github.com/prometheus"
  when: prometheus_version == "git"



- name: set daemon dir for < 0.16
  set_fact:
    prometheus_daemon_dir: "{{ prometheus_install_path }}"
  when: prometheus_version == "git"  or  prometheus_version | version_compare('0.16', '<')

- name: set daemon dir for >= 0.16
  set_fact:
    prometheus_daemon_dir: "{{ prometheus_subdir }}"
  when: prometheus_version != "git"  and  prometheus_version | version_compare('0.16', '>=')



- name: delete the prometheus build directory, if necessary
  file: path="{{ prometheus_download_path }}/prometheus_workdir" state=absent
  when: prometheus_version == "git" and prometheus_rebuild
  ignore_errors: true

- name: create build directory structure, if necessary
  file: path="{{ prometheus_untar_path }}" state=directory
  when: prometheus_version == "git"




- name: download prometheus tarball
  get_url: url="{{ prometheus_tarball_url }}"  dest="{{ prometheus_download_path }}/prometheus.tar.gz"

- name: untar prometheus tarball
  unarchive:
    src: "{{ prometheus_download_path }}/prometheus.tar.gz"
    dest: "{{ prometheus_untar_path }}"
    copy: no

- name: symlink prometheus-master to prometheus
  file:
    src: "{{ prometheus_untar_path }}/prometheus-master"
    dest: "{{ prometheus_untar_path }}/prometheus"
    state: link
  when: prometheus_version == "git"

- name: install temporary Go compiler
  shell: "{{ prometheus_untar_path }}/prometheus-master/scripts/goenv.sh {{ prometheus_download_path }}/prometheus_workdir/go {{ prometheus_download_path }}/prometheus_workdir/gopath"
  when: prometheus_version == "git"

- name: determine installed Go version
  command: "ls {{ prometheus_download_path }}/prometheus_workdir/go/"
  when: prometheus_version == "git"
  changed_when: false
  register: go_version

- name: build prometheus
  command: make build
  args:
    chdir: "{{ prometheus_untar_path }}/prometheus-master"
    creates: prometheus
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ prometheus_download_path }}/prometheus_workdir/go/{{ go_version.stdout }}/bin"
    GOPATH: "{{ prometheus_download_path }}/prometheus_workdir/gopath"
    GOROOT: "{{ prometheus_download_path }}/prometheus_workdir/go/{{ go_version.stdout }}"
  when: prometheus_version == "git"

- name: copy the built prometheus to the install path
  command: "cp -r {{ prometheus_untar_path }}/prometheus-master/{{ item }} {{ prometheus_install_path }}"
  with_items:
    - prometheus
    - promtool
    - consoles
    - console_libraries
  when: prometheus_version == "git"



- name: set permissions, owner and group
  file:
    path: "{{ prometheus_install_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "go-w"
    recurse: yes

- name: mkdir for config and data
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ prometheus_rule_path }}"
    - "{{ prometheus_file_sd_config_path }}"
    - "{{ prometheus_db_path }}"

- name: set prometheus variables
  copy: src="../files/etc-default-prometheus"  dest=/etc/default/prometheus

- name: copy INIT script to server
  template: src="../templates/prometheus.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/prometheus"  mode="a+x"

- name: set INIT status
  service: name=prometheus enabled=yes

- name: copy prometheus main config file from role's default, if necessary
  template: src=../templates/prometheus.yml.j2  dest="{{ prometheus_config_path }}/prometheus.yml"
  when: prometheus_conf_main is not defined
  notify:
    - restart prometheus

- name: copy prometheus main config file from playbook's, if any
  template: src="{{ playbook_dir }}/{{ prometheus_conf_main }}"  dest="{{ prometheus_config_path }}/prometheus.yml"
  when: prometheus_conf_main is defined
  notify:
    - restart prometheus

- name: copy rule files from playbook's, if any
  copy: src={{ playbook_dir }}/{{ item.value.src }}  dest={{ prometheus_rule_path }}/{{ item.value.dest }}
  with_dict: prometheus_rule_files | default({})
  notify:
    - restart prometheus