---
# file: tasks/install-alertmanager.yml
#
# Install Prometheus alertmanager.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- name: set internal variables for convenience
  set_fact:
    prometheus_alertmanager_tarball_url: "https://github.com/prometheus/alertmanager/releases/download/{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-amd64.tar.gz"
    prometheus_untar_path: "{{ prometheus_install_path }}"
  when: prometheus_alertmanager_version != "git" and ansible_userspace_bits == "64"

- name: set internal variables for convenience
  set_fact:
    prometheus_alertmanager_tarball_url: "https://github.com/prometheus/alertmanager/releases/download/{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-386.tar.gz"
    prometheus_untar_path: "{{ prometheus_install_path }}"
  when: prometheus_alertmanager_version != "git" and ansible_userspace_bits == "32"

- name: set internal variables for convenience
  set_fact:
    prometheus_alertmanager_tarball_url: "https://github.com/prometheus/alertmanager/archive/master.tar.gz"
    prometheus_untar_path: /tmp
  when: prometheus_alertmanager_version == "git"

- name: delete the alertmanager directory if it already exists
  file: path="{{ prometheus_download_path }}/alertmanager-master" state=absent
  when: prometheus_alertmanager_version == "git"

- name: download alertmanager tarball
  get_url: url="{{ prometheus_alertmanager_tarball_url }}" dest="{{ prometheus_download_path }}/alertmanager.tar.gz" force=yes

- name: untar alertmanager tarball
  unarchive:
    src: "{{ prometheus_download_path }}/alertmanager.tar.gz"
    dest: "{{ prometheus_untar_path }}"
    copy: no

- name: build alertmanager
  command: make
  args:
    chdir: "{{ prometheus_download_path }}/alertmanager-master"
    creates: alertmanager
  when: prometheus_alertmanager_version == "git"

- name: move the built alertmanager to the install path
  command: "mv {{ prometheus_download_path }}/alertmanager-master/alertmanager {{ prometheus_install_path }}"
  when: prometheus_alertmanager_version == "git"

- name: set permissions, owner and group
  file: path={{ prometheus_install_path }}/alertmanager owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"

- name: mkdir for data
  file:
    path: "{{ prometheus_db_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="

- name: set alertmanager variables
  copy: src="../files/etc-default-alertmanager"  dest=/etc/default/alertmanager

- name: copy INIT script to server
  template: src="../templates/alertmanager.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/alertmanager"  mode="a+x"

- name: set INIT status
  service: name=alertmanager enabled=yes state=restarted

- name: copy alertmanager main config file from playbook's, if any
  template: src="{{ playbook_dir }}/{{ prometheus_alertmanager_conf }}"  dest="{{ prometheus_config_path }}/alertmanager.conf"
  when: prometheus_alertmanager_conf is defined
  notify:
    - restart alertmanager
