---
# file: tasks/install-consul-exporter.yml
#
# Install Prometheus consul-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- block:
    - name: set internal variables for convenience
      set_fact:
        prometheus_consul_exporter_tarball_url: "https://github.com/prometheus/consul_exporter/releases/download/{{ prometheus_consul_exporter_version }}/consul_exporter-{{ prometheus_consul_exporter_version }}.linux-amd64.tar.gz"
      when: ansible_userspace_bits == "64"

    - name: set internal variables for convenience
      set_fact:
        prometheus_consul_exporter_tarball_url: "https://github.com/prometheus/consul_exporter/releases/download/{{ prometheus_consul_exporter_version }}/consul_exporter-{{ prometheus_consul_exporter_version }}.linux-386.tar.gz"
      when: ansible_userspace_bits == "32"

    - name: download and untar consul_exporter tarball
      unarchive:
        src: "{{ prometheus_consul_exporter_tarball_url }}"
        dest: "{{ prometheus_install_path }}"
        copy: no
  when: prometheus_consul_exporter_version != "git"


- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_consul_exporter_tarball_url: "https://github.com/prometheus/consul_exporter/archive/master.tar.gz"

    - name: delete the consul_exporter directory if it already exists
      file: path="{{ prometheus_download_path }}/consul_exporter-master" state=absent

    - name: download and untar consul_exporter tarball
      unarchive:
        src: "{{ prometheus_consul_exporter_tarball_url }}"
        dest: "{{ prometheus_download_path }}"
        copy: no

    - name: build consul_exporter
      command: make
      args:
        chdir: "{{ prometheus_download_path }}/consul_exporter-master"
        creates: consul_exporter
      environment:
        GO15VENDOREXPERIMENT: 1
        GOROOT: "{{ prometheus_goroot }}"
        GOPATH: "{{ prometheus_gopath }}"
        PATH: "{{ ansible_env.PATH }}:{{ prometheus_goroot }}/bin:{{ prometheus_gopath }}/bin"


    - name: copy the built consul_exporter to the install path
      command: "cp {{ prometheus_download_path }}/consul_exporter-master/consul_exporter {{ prometheus_install_path }}"

  when: prometheus_consul_exporter_version == "git"



- name: set permissions, owner and group
  file: path={{ prometheus_install_path }}/consul_exporter owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"

- name: set consul_exporter variables
  copy: src="../files/etc-default-consul_exporter"  dest=/etc/default/consul_exporter

- name: copy INIT script to server
  template: src="../templates/consul_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/consul_exporter"  mode="a+x"

- name: set INIT status
  service: name=consul_exporter enabled=yes state=restarted
