---
# file: tasks/install-consul-exporter.yml
#
# Install Prometheus consul-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#


- name: set internal variables for convenience
  set_fact:
    prometheus_consul_exporter_tarball_url: "https://github.com/prometheus/consul_exporter/releases/download/{{ prometheus_consul_exporter_version }}/consul_exporter-{{ prometheus_consul_exporter_version }}.linux-amd64.tar.gz"
  when: ansible_userspace_bits == "64"

- name: set internal variables for convenience
  set_fact:
    prometheus_consul_exporter_tarball_url: "https://github.com/prometheus/consul_exporter/releases/download/{{ prometheus_consul_exporter_version }}/consul_exporter-{{ prometheus_consul_exporter_version }}.linux-386.tar.gz"
  when: ansible_userspace_bits == "32"



- name: download consul_exporter tarball
  get_url: url="{{ prometheus_consul_exporter_tarball_url }}"  dest="{{ prometheus_download_path }}/consul_exporter.tar.gz"

- name: uutar consul_exporter tarball
  unarchive:
    src: "{{ prometheus_download_path }}/consul_exporter.tar.gz"
    dest: "{{ prometheus_install_path }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "go-w"
    copy: no



- name: set consul_exporter variables
  copy: src="../files/etc-default-consul_exporter"  dest=/etc/default/consul_exporter

- name: copy INIT script to server
  template: src="../templates/consul_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/consul_exporter"  mode="a+x"

- name: set INIT status
  service: name=consul_exporter enabled=yes state=started
