---
# file: tasks/install-node-exporter.yml
#
# Install Prometheus node-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#


- name: set internal variables for convenience
  set_fact:
    prometheus_node_exporter_tarball_url: "https://github.com/prometheus/node_exporter/releases/download/{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz"
  when: ansible_userspace_bits == "64"

- name: set internal variables for convenience
  set_fact:
    prometheus_node_exporter_tarball_url: "https://github.com/prometheus/node_exporter/releases/download/{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-386.tar.gz"
  when: ansible_userspace_bits == "32"



- name: download node_exporter tarball
  get_url: url="{{ prometheus_node_exporter_tarball_url }}"  dest="{{ prometheus_download_path }}/node_exporter.tar.gz"

- name: uutar node_exporter tarball
  unarchive:
    src: "{{ prometheus_download_path }}/node_exporter.tar.gz"
    dest: "{{ prometheus_install_path }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "go-w"
    copy: no



- name: set node_exporter variables
  copy: src="../files/etc-default-node_exporter"  dest=/etc/default/node_exporter

- name: copy INIT script to server
  template: src="../templates/node_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/node_exporter"  mode="a+x"

- name: set INIT status
  service: name=node_exporter enabled=yes state=started
