---
# file: tasks/install-alertmanager.yml
#
# Install Prometheus alertmanager.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- name: set internal variables for convenience
  set_fact:
    prometheus_alertmanager_tarball_url: "https://github.com/prometheus/alertmanager/releases/download/{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-amd64.tar.gz"
    prometheus_alertmanager_untar_path: "{{ prometheus_install_path }}"
  when: prometheus_alertmanager_version != "git" and ansible_userspace_bits == "64"

- name: set internal variables for convenience
  set_fact:
    prometheus_alertmanager_tarball_url: "https://github.com/prometheus/alertmanager/releases/download/{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-386.tar.gz"
    prometheus_alertmanager_untar_path: "{{ prometheus_install_path }}"
  when: prometheus_alertmanager_version != "git" and ansible_userspace_bits == "32"

- name: set internal variables for convenience
  set_fact:
    prometheus_alertmanager_tarball_url: "https://github.com/prometheus/alertmanager/archive/master.tar.gz"
    prometheus_alertmanager_untar_path: "{{ prometheus_download_path }}"
  when: prometheus_alertmanager_version == "git"


- name: delete the alertmanager build directory, if necessary
  file: path="{{ prometheus_alertmanager_untar_path }}/alertmanager-master" state=absent
  when: prometheus_alertmanager_version == "git" and prometheus_rebuild




- name: download alertmanager tarball
  get_url: url="{{ prometheus_alertmanager_tarball_url }}" dest="{{ prometheus_download_path }}/alertmanager.tar.gz" force=yes

- name: untar alertmanager tarball
  unarchive:
    src: "{{ prometheus_download_path }}/alertmanager.tar.gz"
    dest: "{{ prometheus_alertmanager_untar_path }}"
    copy: no

- name: build alertmanager source code
  command: make
  args:
    chdir: "{{ prometheus_alertmanager_untar_path }}/alertmanager-master"
    creates: alertmanager
  when: prometheus_alertmanager_version == "git"

- name: copy the built alertmanager to the install path
  command: "cp {{ prometheus_alertmanager_untar_path }}/alertmanager-master/alertmanager {{ prometheus_install_path }}"
  args:
    creates: "{{ prometheus_install_path }}/alertmanager"
  when: prometheus_alertmanager_version == "git"



- name: set permissions, owner and group
  file:
    path: "{{ prometheus_install_path }}/alertmanager"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "go-w"

- name: mkdir for alertmanager data (silences.json for now)
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ prometheus_alertmanager_db_path }}"

- name: set alertmanager variables
  copy: src="../files/etc-default-alertmanager"  dest=/etc/default/alertmanager

- name: copy INIT script to server
  template: src="../templates/alertmanager.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/alertmanager"  mode="a+x"

- name: set INIT status
  service: name=alertmanager enabled=yes

#- name: set INIT status and start
#  service: name=alertmanager state=started
#  when: prometheus_use_service|bool

- name: install alertmanager config file from playbook's, if any
  template: src="{{ playbook_dir }}/{{ prometheus_alertmanager_conf }}"  dest="{{ prometheus_config_path }}/alertmanager.conf"
  when: prometheus_alertmanager_conf is defined
  notify:
    - restart alertmanager

- name: install default (empty) alertmanager config file, if necessary
  copy: src="../files/alertmanager.empty.conf"  dest="{{ prometheus_config_path }}/alertmanager.conf"
  when: prometheus_alertmanager_conf is not defined
  notify:
    - restart alertmanager
